parameters:
    kunstmaan_media.generator.path.default.class: 'Kunstmaan\MediaBundle\Helper\Generator\DefaultPathGenerator'
    kunstmaan_media.generator.uuid.default.class: 'Kunstmaan\MediaBundle\Helper\Generator\DefaultUuidGenerator'
    
services:
    kunstmaan_media.generator.path.default:
        class: %kunstmaan_media.generator.path.default.class%
    kunstmaan_media.generator.uuid.default:
        class: %kunstmaan_media.generator.uuid.default.class%
