parameters:
    
    kunstmaan_media.media_handler.remote_slide.class: 'Kunstmaan\MediaBundle\Helper\RemoteSlide\RemoteSlideHandler'
    kunstmaan_media.media_handler.remote_video.class: 'Kunstmaan\MediaBundle\Helper\RemoteVideo\RemoteVideoHandler'
    kunstmaan_media.media_handler.image.class: 'Kunstmaan\MediaBundle\Helper\Image\ImageHandler'
    kunstmaan_media.media_handler.file.class: 'Kunstmaan\MediaBundle\Helper\File\FileHandler'
    kunstmaan_media.image.manipulator.imagine.class: 'Kunstmaan\MediaBundle\Helper\Manipulator\ImagineImageManipulator'
    aviary_api_key: null

services:

    kunstmaan_media.image.manipulator.imagine:
        class: "%kunstmaan_media.image.manipulator.imagine.class%"
        arguments: ["@liip_imagine"]

    kunstmaan_media.media_handlers.remote_slide:
        class: "%kunstmaan_media.media_handler.remote_slide.class%"
        tags:
            -  { name: 'kunstmaan_media.media_handler' }
            
    kunstmaan_media.media_handlers.remote_video:
        class: "%kunstmaan_media.media_handler.remote_video.class%"
        tags:
            -  { name: 'kunstmaan_media.media_handler' }
            
    kunstmaan_media.media_handlers.image:
        class: "%kunstmaan_media.media_handler.image.class%"
        arguments: ["@kunstmaan_media.image.manipulator.imagine", "%aviary_api_key%"]
        tags:
            -  { name: 'kunstmaan_media.media_handler' }
            
    kunstmaan_media.media_handlers.file:
        class: "%kunstmaan_media.media_handler.file.class%"
        tags:
            -  { name: 'kunstmaan_media.media_handler' }
    