services:
    kunstmaan_media.imagick:
        class: 'Imagick'

    kunstmaan_media.pdf_transformer:
        class: Kunstmaan\MediaBundle\Helper\Transformer\PdfTransformer
        arguments: ['@kunstmaan_media.imagick']

    kunstmaan_media.media_handlers.pdf:
        class: Kunstmaan\MediaBundle\Helper\File\PdfHandler
        parent: kunstmaan_media.media_handlers.file
        arguments:
            index_0: 1 # Override the priority value of the parent service
        calls:
            - [ setWebPath, [ '%kernel.project_dir%/public' ] ]
            - [ setPdfTransformer, [ '@kunstmaan_media.pdf_transformer' ]]
        tags:
            -  { name: 'kunstmaan_media.media_handler' }

    kunstmaan_media.command.createpdfpreview:
        class: Kunstmaan\MediaBundle\Command\CreatePdfPreviewCommand
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@kunstmaan_media.pdf_transformer'
            - '%kunstmaan_media.web_root%'
            - '%kunstmaan_media.enable_pdf_preview%'
        tags:
            - { name: console.command }
