KunstmaanMediaBundle_media:
    resource: "@KunstmaanMediaBundle/Controller/MediaController.php"
    type:     annotation
    prefix:   /admin/media
        
KunstmaanMediaBundle_aviary:
    resource: "@KunstmaanMediaBundle/Controller/AviaryController.php"
    type:     annotation
    prefix:   /
        
KunstmaanMediaBundle_media_chooser:
    resource: "@KunstmaanMediaBundle/Controller/ChooserController.php"
    type:     annotation
    prefix:   /admin/media
        
KunstmaanMediaBundle_media_folder:
    resource: "@KunstmaanMediaBundle/Controller/FolderController.php"
    type:     annotation
    prefix:   /admin/media/folder  
   
KunstmaanMediaBundle_video:
    resource: "@KunstmaanMediaBundle/Controller/VideoController.php"
    type:     annotation
    prefix:   /admin/media/video
     
KunstmaanMediaBundle_slide:
    resource: "@KunstmaanMediaBundle/Controller/SlideController.php"
    type:     annotation
    prefix:   /admin/media/slide

KunstmaanMediaBundle_metadata:
    resource: "@KunstmaanMediaBundle/Controller/MediaMetadataController.php"
    type:     annotation
    prefix:   /admin/media/metadata
        
_imagine:
    resource: .
    type:     imagine
    

                 