KunstmaanMediaBundle_media:
    resource: "@KunstmaanMediaBundle/Controller/MediaController.php"
    type:     annotation
    prefix:   /admin/media

KunstmaanMediaBundle_aviary:
    resource: "@KunstmaanMediaBundle/Controller/AviaryController.php"
    type:     annotation

KunstmaanMediaBundle_media_imagegallery:
    resource: "@KunstmaanMediaBundle/Controller/ImageGalleryController.php"
    type:     annotation
    prefix:   /admin/media/imagegallery/

KunstmaanMediaBundle_media_videogallery:
    resource: "@KunstmaanMediaBundle/Controller/VideoGalleryController.php"
    type:     annotation
    prefix:   /admin/media/videogallery

KunstmaanMediaBundle_media_filegallery:
    resource: "@KunstmaanMediaBundle/Controller/FileGalleryController.php"
    type:     annotation
    prefix:   /admin/media/filegallery

KunstmaanMediaBundle_media_slidegallery:
    resource: "@KunstmaanMediaBundle/Controller/SlideGalleryController.php"
    type:     annotation
    prefix:   /admin/media/slidegallery

KunstmaanMediaBundle_media_gallery:
    resource: "@KunstmaanMediaBundle/Controller/GalleryController.php"
    type:     annotation
    prefix:   /admin/media/gallery

KunstmaanMediaBundle_image:
    resource: "@KunstmaanMediaBundle/Controller/ImageController.php"
    type:     annotation
    prefix:   /admin/media/image

KunstmaanMediaBundle_video:
    resource: "@KunstmaanMediaBundle/Controller/VideoController.php"
    type:     annotation
    prefix:   /admin/media/video

KunstmaanMediaBundle_file:
    resource: "@KunstmaanMediaBundle/Controller/FileController.php"
    type:     annotation
    prefix:   /admin/media/file

KunstmaanMediaBundle_slide:
    resource: "@KunstmaanMediaBundle/Controller/SlideController.php"
    type:     annotation
    prefix:   /admin/media/slide
