KunstmaanMediaBundle_media:
    resource: "@KunstmaanMediaBundle/Controller/MediaController.php"
    type:     annotation
    prefix:   /{_locale}/admin/media
    requirements:
        _locale: en|nl|fr
        
KunstmaanMediaBundle_aviary:
    resource: "@KunstmaanMediaBundle/Controller/AviaryController.php"
    type:     annotation
        
KunstmaanMediaBundle_media_imagegallery:
    resource: "@KunstmaanMediaBundle/Controller/ImageGalleryController.php"
    type:     annotation
    prefix:   /{_locale}/admin/media/imagegallery/
    requirements:
        _locale: en|nl|fr
        
KunstmaanMediaBundle_media_folder:
    resource: "@KunstmaanMediaBundle/Controller/FolderController.php"
    type:     annotation
    prefix:   /{_locale}/admin/media/folder
    requirements:
        _locale: en|nl|fr        

KunstmaanMediaBundle_image:
    resource: "@KunstmaanMediaBundle/Controller/ImageController.php"
    type:     annotation
    prefix:   /{_locale}/admin/media/image
    requirements:
        _locale: en|nl|fr
        
KunstmaanMediaBundle_video:
    resource: "@KunstmaanMediaBundle/Controller/VideoController.php"
    type:     annotation
    prefix:   /{_locale}/admin/media/video
    requirements:
        _locale: en|nl|fr
        
KunstmaanMediaBundle_file:
    resource: "@KunstmaanMediaBundle/Controller/FileController.php"
    type:     annotation
    prefix:   /{_locale}/admin/media/file
    requirements:
        _locale: en|nl|fr
        
KunstmaanMediaBundle_slide:
    resource: "@KunstmaanMediaBundle/Controller/SlideController.php"
    type:     annotation
    prefix:   /{_locale}/admin/media/slide
    requirements:
        _locale: en|nl|fr

                 