parameters:
    kunstmaan_media.media_manager.class: 'Kunstmaan\MediaBundle\Helper\MediaManager'
    kunstmaan_media.menu.adaptor.class: 'Kunstmaan\MediaBundle\Helper\Menu\MediaMenuAdaptor'
    kunstmaan_media.listener.doctrine.class: 'Kunstmaan\MediaBundle\EventListener\DoctrineMediaListener'
    kunstmaan_media.form.type.media.class: 'Kunstmaan\MediaBundle\Form\Type\MediaType'
    kunstmaan_media.media_creator_service.class: 'Kunstmaan\MediaBundle\Helper\Services\MediaCreatorService'


services:
    liip_imagine.data.loader.stream.profile_photos:
        class: "%liip_imagine.data.loader.stream.class%"
        arguments:
            - "@liip_imagine"
            - ''
        tags:
            - { name: 'liip_imagine.data.loader', loader: 'kunstmaan_media_thumbloader' }

    kunstmaan_media.media_manager:
        class: "%kunstmaan_media.media_manager.class%"

    kunstmaan_media.menu.adaptor:
        class: "%kunstmaan_media.menu.adaptor.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }

    kunstmaan_media.listener.doctrine:
        class: "%kunstmaan_media.listener.doctrine.class%"
        arguments: ["@kunstmaan_media.media_manager"]
        tags:
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate' }
            - { name: 'doctrine.event_listener', event: 'postPersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }
            - { name: 'doctrine.event_listener', event: 'preRemove' }

    form.type.media:
        class: "%kunstmaan_media.form.type.media.class%"
        arguments:
            - "@kunstmaan_media.media_manager"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: media }

    kunstmaan_media.media_creator_service:
        class: "%kunstmaan_media.media_creator_service.class%"
        calls:
            - [ setEntityManager, [ "@doctrine.orm.entity_manager" ] ]
