parameters:
#    kunstmaan_westtoerapp.example.class: Kunstmaan\WesttoerAppBundle\Example

services:
    kunstmaan_media.menu.adaptor:
        class: Kunstmaan\MediaBundle\Helper\Menu\MediaMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
            