parameters:

services:
    media.menu.adaptor:
        class: Kunstmaan\MediaBundle\Helper\Menu\MediaMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            -  { name: 'admin_menu.adaptor' }
            