parameters:
    kunstmaan_media.listener.doctrine.class: 'Kunstmaan\MediaBundle\EventListener\DoctrineMediaListener'

services:
    kunstmaan_media.menu.adaptor:
        class: Kunstmaan\MediaBundle\Helper\Menu\MediaMenuAdaptor
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
            
    kunstmaan_media.listener.doctrine:
        class: "%kunstmaan_media.listener.doctrine.class%"
        arguments: ["@kunstmaan_media.media_manager"]
        tags:
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate' }
            - { name: 'doctrine.event_listener', event: 'postPersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }
            - { name: 'doctrine.event_listener', event: 'preRemove' }