parameters:
    kunstmaan_media.media_manager.class: 'Kunstmaan\MediaBundle\Helper\MediaManager'
    kunstmaan_media.listener.doctrine.class: 'Kunstmaan\MediaBundle\EventListener\DoctrineMediaListener'
    kunstmaan_media.form.type.media.class: 'Kunstmaan\MediaBundle\Form\Type\MediaType'


services:
    liip_imagine.data.loader.stream.profile_photos:
        class: "%liip_imagine.data.loader.stream.class%"
        arguments:
            - "@liip_imagine"
            - ''
        tags:
            - { name: 'liip_imagine.data.loader', loader: 'kunstmaan_media_thumbloader' }
    kunstmaan_media.media_manager:
        class: "%kunstmaan_media.media_manager.class%"

    kunstmaan_media.configure_menu_listener:
        class: Kunstmaan\MediaBundle\EventListener\ConfigureMenuListener
        arguments: ["@request"]
        scope: request
        tags:
            - { name: 'kernel.event_listener', event: 'kunstmaan_admin.configureMenu', method: 'onMenuConfigure' }

    kunstmaan_media.configure_menu_children_listener:
        class: Kunstmaan\MediaBundle\EventListener\ConfigureMenuChildrenListener
        arguments: ["@request", "@doctrine.orm.entity_manager"]
        scope: request
        tags:
            - { name: 'kernel.event_listener', event: 'kunstmaan_admin.configureMenuChildren', method: 'onMenuChildrenConfigure' }

    kunstmaan_media.listener.doctrine:
        class: "%kunstmaan_media.listener.doctrine.class%"
        arguments: ["@kunstmaan_media.media_manager"]
        tags:
            - { name: 'doctrine.event_listener', event: 'prePersist' }
            - { name: 'doctrine.event_listener', event: 'preUpdate' }
            - { name: 'doctrine.event_listener', event: 'postPersist' }
            - { name: 'doctrine.event_listener', event: 'postUpdate' }
            - { name: 'doctrine.event_listener', event: 'preRemove' }
            
    form.type.media:
        class: "%kunstmaan_media.form.type.media.class%"
        arguments:
            - "@kunstmaan_media.media_manager"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: media }