language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm


before_script:
  - sudo apt-get install -qq imagemagick ghostscript
  - composer selfupdate
  - composer --prefer-source install

script: phpunit --debug

notifications:
  email:
    - travis@kunstmaan.be
