<?php
namespace Kunstmaan\MediaBundle\Tests\Entity;

use Kunstmaan\MediaBundle\Entity\Folder;
use Kunstmaan\MediaBundle\Entity\Media;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-28 at 14:19:20.
 */
class FolderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Folder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     * @covers Kunstmaan\MediaBundle\Entity\Folder::__construct
     */
    protected function setUp()
    {
        $this->object = new Folder();
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::getName
     * @covers Kunstmaan\MediaBundle\Entity\Folder::setName
     */
    public function testGetSetName()
    {
        $this->object->setName('abc');
        $this->assertEquals('abc', $this->object->getName());
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::getRel
     * @covers Kunstmaan\MediaBundle\Entity\Folder::setRel
     */
    public function testGetSetRel()
    {
        $this->object->setRel('bcd');
        $this->assertEquals('bcd', $this->object->getRel());
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::getCreatedAt
     * @covers Kunstmaan\MediaBundle\Entity\Folder::setCreatedAt
     */
    public function testGetSetCreatedAt()
    {
        $date = new \DateTime();
        $this->object->setCreatedAt($date);
        $this->assertEquals($date, $this->object->getCreatedAt());
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::getUpdatedAt
     * @covers Kunstmaan\MediaBundle\Entity\Folder::setUpdatedAt
     */
    public function testGetSetUpdatedAt()
    {
        $date = new \DateTime();
        $this->object->setUpdatedAt($date);
        $this->assertEquals($date, $this->object->getUpdatedAt());
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::getParent
     * @covers Kunstmaan\MediaBundle\Entity\Folder::setParent
     */
    public function testGetParent()
    {
        $parent = new Folder();
        $parent->setId(45);
        $this->object->setParent($parent);
        $this->assertEquals(45, $this->object->getParent()->getId());
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::setDeleted
     * @covers Kunstmaan\MediaBundle\Entity\Folder::isDeleted
     */
    public function testSetDeleted()
    {
        $this->object->setDeleted(true);
        $this->assertEquals(true, $this->object->isDeleted());
        $this->object->setDeleted(false);
        $this->assertEquals(false, $this->object->isDeleted());
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::getTranslatableLocale
     * @covers Kunstmaan\MediaBundle\Entity\Folder::setTranslatableLocale
     */
    public function testGetSetTranslatableLocale()
    {
        $this->object->setTranslatableLocale('nl');
        $this->assertEquals('nl', $this->object->getTranslatableLocale());
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::getParents
     */
    public function testGetParents()
    {
        $root = new Folder();
        $root->setId(1);

        $subFolder = new Folder();
        $subFolder->setId(2);
        $subFolder->setParent($root);

        $subSubFolder = new Folder();
        $subSubFolder->setId(3);
        $subSubFolder->setParent($subFolder);

        $parents = array($root, $subFolder);
        $this->assertEquals($parents, $subSubFolder->getParents());
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::addChild
     */
    public function testAddChild()
    {
        $this->assertCount(0, $this->object->getChildren());

        $subFolder = new Folder();
        $subFolder->setId(2);
        $this->object->addChild($subFolder);

        $this->assertCount(1, $this->object->getChildren());
        $this->assertEquals($this->object, $subFolder->getParent());
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::addMedia
     */
    public function testAddMedia()
    {
        $this->assertCount(0, $this->object->getMedia());

        $media = new Media();
        $this->object->addMedia($media);

        $this->assertCount(1, $this->object->getMedia());
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::getMedia
     */
    public function testGetMedia()
    {
        $media = new Media();
        $this->object->addMedia($media);

        $deletedMedia = new Media();
        $deletedMedia->setDeleted(true);
        $this->object->addMedia($deletedMedia);

        $this->assertCount(1, $this->object->getMedia());
        $this->assertCount(1, $this->object->getMedia(false));
        $this->assertCount(2, $this->object->getMedia(true));

        $folderMedia = $this->object->getMedia(false);
        $this->assertContains($media, $folderMedia);
        $this->assertNotContains($deletedMedia, $folderMedia);

        $folderMedia = $this->object->getMedia(true);
        $this->assertContains($media, $folderMedia);
        $this->assertContains($deletedMedia, $folderMedia);
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::getChildren
     */
    public function testGetChildren()
    {
        $child = new Folder();
        $this->object->addChild($child);

        $deletedChild = new Folder();
        $deletedChild->setDeleted(true);
        $this->object->addChild($deletedChild);

        $this->assertCount(1, $this->object->getChildren());
        $this->assertCount(1, $this->object->getChildren(false));
        $this->assertCount(2, $this->object->getChildren(true));

        $children = $this->object->getChildren(false);
        $this->assertContains($child, $children);
        $this->assertNotContains($deletedChild, $children);

        $children = $this->object->getChildren(true);
        $this->assertContains($child, $children);
        $this->assertContains($deletedChild, $children);
    }

    /**
     * @covers Kunstmaan\MediaBundle\Entity\Folder::hasActive
     */
    public function testHasActive()
    {
        $root = new Folder();
        $root->setId(1);

        $subFolder = new Folder();
        $subFolder->setId(2);
        $subFolder->setParent($root);

        $subFolder2 = new Folder();
        $subFolder2->setId(4);
        $subFolder2->setParent($root);

        $subSubFolder = new Folder();
        $subSubFolder->setId(3);
        $subSubFolder->setParent($subFolder);

        $this->assertTrue($subSubFolder->hasActive(2));
        $this->assertFalse($subSubFolder->hasActive(4));
    }

}
